# core/suggestions_llm_schema.py

SUGGESTIONS_LLM_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "summary": {
            "type": "array",
            "description": "Suggestions for the top-level summary section.",
            "items": {
                "type": "object",
                "properties": {
                    "impact": {"type": "string", "enum": ["HIGH", "MEDIUM", "LOW"]},
                    "reason": {"type": "string"},
                    "after_example": {"type": "string"},
                },
                "required": ["impact", "reason", "after_example"],
            },
        },
        "bullets": {
            "type": "array",
            "description": (
                "Bullet-level suggestions. Each item refers to a slot_index "
                "generated by the planner; you only fill after_example."
            ),
            "items": {
                "type": "object",
                "properties": {
                    "slot_index": {"type": "integer"},
                    "after_example": {"type": "string"},
                },
                "required": ["slot_index", "after_example"],
            },
        },
        "skills": {
            "type": "array",
            "description": "Skill add/remove suggestions.",
            "items": {
                "type": "object",
                "properties": {
                    "impact": {"type": "string", "enum": ["HIGH", "MEDIUM", "LOW"]},
                    "reason": {"type": "string"},
                    "to_add": {"type": "array", "items": {"type": "string"}},
                    "to_remove": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["impact", "reason", "to_add", "to_remove"],
            },
        },
        "cleanup": {
            "type": "array",
            "description": "Cleanup suggestions for buzzwords / stopwords.",
            "items": {
                "type": "object",
                "properties": {
                    "impact": {"type": "string", "enum": ["HIGH", "MEDIUM", "LOW"]},
                    "reason": {"type": "string"},
                    "after_example": {"type": "string"},
                },
                "required": ["impact", "reason", "after_example"],
            },
        },
    },
    "required": ["summary", "bullets", "skills", "cleanup"],
}
